apiVersion: apps/v1
kind: Deployment
metadata:
  name: threescaleAPI
spec:
  replicas: 1
  selector:
    matchLabels:
      name: threescaleAPI
  template:
    metadata:
      labels:
        name: threescaleAPI
    spec:
      serviceAccountName: threescaleAPI
      containers:
        - name: threescaleAPI
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - threescaleAPI
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "threescaleAPI"
