apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: limits.api.3scale.net
spec:
  group: api.3scale.net
  names:
    kind: LIMIT
    listKind: LIMITList
    plural: limits
    singular: limit
  scope: Namespaced
  version: v1alpha1
