apiVersion: apps/v1
kind: Deployment
metadata:
  name: apioperator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apioperator
  template:
    metadata:
      labels:
        name: apioperator
    spec:
      containers:
        - name: apioperator
          image: quay.io/3scale/api-operator:v0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - apioperator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "apioperator"
