kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ostia-operator
rules:
- apiGroups:
  - ostia.3scale.net
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "ostia.3scale.net"
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-ostia-operator
subjects:
- kind: ServiceAccount
  name: ostia
roleRef:
  kind: Role
  name: ostia-operator
  apiGroup: rbac.authorization.k8s.io
